name: Checkin

on:
  schedule:
    # 此处为UTC时间0点、1点和23点，对应北京时间+8为8点、9点和7点
    - cron: '0 23,0,1,2,3,4 * * *'
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  checkin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Set up Chromedriver
      uses: nanasess/setup-chromedriver@master

    - name: Environment
      run: |
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        google-chrome --version

    - name: Check in
      run: |
        python checkin.py
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TGCHATID: ${{ secrets.TGCHATID }}
        BOTTOKEN: ${{ secrets.BOTTOKEN }}
        
