name: Checkin

on:
  schedule:
    # 此处为UTC时间0点、1点和23点，对应北京时间+8为8点、9点和7点
    - cron: '0 0,1,2,23,24 * * *'
  watch:
    types: started

env:
  TZ: Asia/Shanghai

jobs:
  checkin:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: 打卡
      run: |
        python checkin.py
      env:
        USERNAME: ${{ secrets.USERNAME }}
        PASSWORD: ${{ secrets.PASSWORD }}
        TGCHATID: ${{ secrets.TGCHATID }}
        BOTTOKEN: ${{ secrets.BOTTOKEN }}
        
